import logging
from fastapi import APIRouter, File, UploadFile, HTTPException, Depends
from fastapi.concurrency import run_in_threadpool
from sqlalchemy.orm import Session

from app.api.deps import get_db
from app.models.policy import Policy
from app.schemas.policy import (
    PolicyUploadResponse,
    PolicyProcessResponse,
    PolicyListResponse,
    PolicyDetail,
    PolicyAnalyzeRequest,
    PolicyAnalyzeResponse,
)
from app.services.policy_service import save_policy_file
from app.services.policy_pipeline import process_policy
from app.services.chat_service import store_clauses

# Configure logger for route tracking
logger = logging.getLogger(__name__)

router = APIRouter()

@router.get("/", response_model=PolicyListResponse)
def list_policies(db: Session = Depends(get_db)):
    """
    List all uploaded policies and their current status.
    """
    policies = db.query(Policy).order_by(Policy.created_at.desc()).all()
    return {"policies": policies}

@router.get("/{file_id}", response_model=PolicyDetail)
def get_policy(file_id: str, db: Session = Depends(get_db)):
    """
    Get detailed information about a specific policy.
    """
    policy = db.query(Policy).filter(Policy.file_id == file_id).first()
    if not policy:
        raise HTTPException(status_code=404, detail="Policy not found")
    return policy

@router.post("/upload", response_model=PolicyUploadResponse)
async def upload_policy(file: UploadFile = File(...), db: Session = Depends(get_db)):
    """
    Ingest a policy PDF file for analysis and save metadata to the database.
    """
    if not file:
        raise HTTPException(status_code=400, detail="No file uploaded")
    
    # Step A: save PDF bytes to disk under uploads/<uuid>.pdf
    logger.info(f"💾 Ingesting file: {file.filename}")
    file_id = await run_in_threadpool(save_policy_file, file)
    
    # Step B: INSERT into `policies` table
    # Data shape: { file_id: uuid-str, filename: str, status: "pending" }
    # id and created_at are auto-generated by Supabase
    # DEBUG: print("Inserting policy:", file_id, file.filename)
    new_policy = Policy(
        file_id=file_id,
        filename=file.filename,
        status="pending"
    )
    db.add(new_policy)   # stages INSERT INTO policies (file_id, filename, status)
    db.commit()          # sends to Supabase
    db.refresh(new_policy)  # reads back id, created_at
    
    return PolicyUploadResponse(
        file_id=file_id,
        filename=file.filename
    )

@router.post("/process/{file_id}", response_model=PolicyProcessResponse)
async def process_policy_endpoint(file_id: str, db: Session = Depends(get_db)):
    """
    Execute the full policy processing pipeline for a given file_id:
    PDF Extraction -> Text Normalization -> NLP Clause Segmentation.
    """
    # Step A: verify the policy row exists (was created during /upload)
    policy = db.query(Policy).filter(Policy.file_id == file_id).first()
    if not policy:
        raise HTTPException(status_code=404, detail="File ID not found in database registry")
    
    # Step B: UPDATE policies SET status='processing'
    policy.status = "processing"
    db.commit()
    
    logger.info(f"⚙️ Processing request for file_id={file_id}")
    try:
        outcome = await run_in_threadpool(process_policy, file_id)
        
        # Step C: UPDATE policies SET status='completed', num_clauses=N, clauses=[...]
        # clauses is stored as a JSON array in the `clauses` column (type: JSON)
        # DEBUG: print("Storing clauses count:", outcome.get("num_clauses"), "sample:", outcome.get("clauses", [])[:2])
        policy.status = "completed"
        policy.num_clauses = outcome.get("num_clauses", 0)
        policy.clauses = outcome.get("clauses", [])  # JSON array → stored as JSONB in Supabase
        db.commit()

        # Step D: populate in-memory RAG store + persist FAISS index for chat service
        store_clauses(outcome.get("clauses", []), policy_id=file_id)

        return PolicyProcessResponse(**outcome)
        
    except Exception as e:
        # Step E: UPDATE policies SET status='failed' on any error
        policy.status = "failed"
        db.commit()
        logger.error(f"❌ Processing failed for {file_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

from app.services.dataset_ingestion_service import get_dataset_by_id, df_from_dataset
from app.services.policy_analysis_orchestrator import run_policy_analysis

import io
import pdfplumber

@router.post("/analyze", response_model=PolicyAnalyzeResponse)
def analyze_policies(
    body: PolicyAnalyzeRequest,
    db: Session = Depends(get_db),
):
    """
    Run end-to-end multi-policy simulation, comparison, explainability,
    impact analysis, and ranking against a stored dataset.
    """
    dataset_row = get_dataset_by_id(body.dataset_id, db)
    if dataset_row is None:
        raise HTTPException(status_code=404, detail=f"Dataset '{body.dataset_id}' not found.")

    df = df_from_dataset(dataset_row)

    new_policies = [p.model_dump() for p in body.new_policies]

    try:
        result = run_policy_analysis(
            dataset=df,
            baseline_rules=body.baseline_rules,
            new_policies=new_policies,
        )
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    # Ensure large lists (e.g. explanations) are pagination-ready:
    # each policy entry carries its explanations as a top-level list
    # so callers can slice by index range without re-running the pipeline.
    for policy in result["policies"]:
        policy["explanation_count"] = len(policy.get("explanations", []))

    return result


@router.post("/extract")
async def extract_clauses_direct(file: UploadFile = File(...)):
    """
    Accepts a PDF file upload and extracts clauses by reading all pages via pdfplumber
    and splitting the resulting text by newline. Returns a clean list of clauses.
    """
    if not file or not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Please upload a valid PDF document.")
    
    print("FILE RECEIVED:", file.filename)
    
    try:
        file_content = await file.read()
        
        extracted_text = ""
        with pdfplumber.open(io.BytesIO(file_content)) as pdf:
            for page in pdf.pages:
                page_text = page.extract_text()
                if page_text:
                    extracted_text += page_text + "\n"
        
        if not extracted_text:
            print("EXTRACTED CLAUSES: []")
            return {"clauses": []}
        
        clauses = [
            line.strip() 
            for line in extracted_text.split("\n") 
            if line.strip()
        ]
        
        # Populate RAG store so chat service can retrieve policy context
        # policy_id derived from filename (no DB record in this fast path)
        policy_id = file.filename.replace(".pdf", "").replace(" ", "_")
        store_clauses(clauses, policy_id=policy_id)
        print("EXTRACTED CLAUSES:", len(clauses), "| RAG stored for policy_id:", policy_id)
        return {"clauses": clauses, "policy_id": policy_id}
        
    except Exception as e:
        print(f"ERROR DURING EXTRACTION: {str(e)}")
        return {"clauses": []}
